### ISSUE TITLE
Feature request: time period selection Dashboard

### ISSUE THREAD

**Issue by rhiaro** [mtierltd/timetracker#96] opened 2021-02-24 10:32 UTC
It would be super cool to be able to choose the date range used for the Dashboard pie chart. (At the time of writing it always shows the last 30 days.)

Even cooler would be a timeslider that shows the pie slices moving, but I'll be happy with start/end dropdowns :)

**Comment by puthre** [comment] 2021-02-24 11:41
Duplicate of #94

**Closed by puthre** 2021-02-24 11:41 UTC

**Comment by rhiaro** [comment] 2021-02-24 11:51
#94 is closed though with only the colours part fixed; still on the radar?

**Comment by puthre** [comment] 2021-02-24 13:13
@rhiaro both colors and time spans are implemented. Not sure if they are included in the latest build.

**Comment by rhiaro** [comment] 2021-02-24 13:21
@puthre Ah! I didn't see the commit, but wasn't looking closely enough. Thanks!
