### ISSUE TITLE
[Feature Request] Connect Tasks with Time Tracker

### ISSUE THREAD

**Issue by pyretta** [mtierltd/timetracker#14] opened 2019-09-05 11:55 UTC
Hello,
nice app for recording working time for projects. Thank you for sharing it with the community.

I think it would be interesting for all users to be able to connect already created tasks to the Time Tracker app. So we could easily track the time it took us to complete a particular task, without having to copy the name or description of the task. Maybe it could be automatically added to the Time Tracker app as soon as a task is marked as done. Or even when the percentage under "completed" has increased.

This would certainly be a very good help for many users.

**Comment by reinerj** [comment] 2019-09-09 08:22
This could be done only as an optional feature as not everybody does use tasks and not everybody does use tasks. But I agree it would make sense. We will possible add this in a future release.

Regards
Reiner

**Comment by lewie** [comment] 2019-12-10 07:38
Hi,
thanks for sharing this very useful app!!!

Same I think, it would be useful to connect Time Tracker with kanban Deck-App, where Projects and Tasks can be organized.

**Comment by puthre** [comment] 2020-11-17 11:08
Duplicate of #2

**Closed by puthre** 2020-11-17 11:08 UTC
Labels: assigned to milestone, future development
